### Numpy Mastery Assignment
- Answer all questions
- Submission : 20th September 2022

In [2]:
import numpy as np

1. Create a 1D array of numbers from 0 to 9

In [3]:
numbers = np.arange(0,10)
numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3x3 numpy of all True 

In [4]:
true_three = np.full((3,3), True)
true_three

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Create an array of numbers from 20 to 39

In [5]:
arr_num = np.arange(20,40)
arr_num

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

4. Replace all odd numbers in Q3 by -1

In [6]:
arr_num [arr_num %2 != 0 ] = -1
arr_num

array([20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1, 36,
       -1, 38, -1])

5. Create two arrays of length 10 and print out  common items in both arrays

In [9]:
arr_1 = np.arange(1,11)
arr_2 = np.arange(7,18)

np.intersect1d(arr_1,arr_2)

array([ 7,  8,  9, 10])

6.  Create a 5x5 identity matrix

In [10]:
id_mat = np.eye(5)
id_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

7. In the code cell below define and print a set of arrays defined x, y and z. The array x should be take the form [10 12 9 2 20], y should have  101  values from  10  to  20  inclusive and z should be a  2×3  array of ones.

In [14]:
x = np.array([10, 12, 9, 2, 20])
y = np.linspace(10,20,101)
z = np.ones((2,3))

print(f' x: {x} \n y: {y} \n z:{z}')

 x: [10 12  9  2 20] 
 y: [10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1 11.2 11.3
 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5 12.6 12.7
 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9 14.  14.1
 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3 15.4 15.5
 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7 16.8 16.9
 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1 18.2 18.3
 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5 19.6 19.7
 19.8 19.9 20. ] 
 z:[[1. 1. 1.]
 [1. 1. 1.]]


8.Using the available Numpy functions on array x from problem  7 , find the average and the standard deviation of the value in this array. Redefine x as an array with all these values sorted in numerical order.

In [19]:
mean = np.mean(x)
stdev = np.std(x)
x = np.sort(x)

print(f' mean:{mean} \n stdev:{stdev} \n x:{x}')


 mean:10.6 
 stdev:5.782732917920384 
 x:[ 2  9 10 12 20]


9. Create a 10x10 array with random values and find the minimum and maximum values

In [28]:
arr_rand = np.random.randint(10,200,(10,10))
rand_max = np.max(arr_rand)
rand_min = np.min(arr_rand)

print(f' arr_rand:{arr_rand}\n rand_max:{rand_max}\n rand_min:{rand_min}')

 arr_rand:[[ 47  21 161  74  33  70  24  64 101 140]
 [126 188 129  68  88 172 127 130 135 180]
 [ 24  42 173 135 106  40 113 192  14  34]
 [100  66  73 187 115  41 177  50 111 102]
 [ 25  12 111 125  86  67  35 134 121 137]
 [123  18  77  83 140 127 106  88 153  11]
 [111 159 152  56  16 131 130  36  48 156]
 [119  68 101 168 139 162 163 147 126 102]
 [167  63 144 173  80  69 194  83  73 185]
 [138 106 134 129  55  23 169 139  54 187]]
 rand_max:194
 rand_min:11


10. Create a 3x3 matrix with values ranging from 0 to 8

In [41]:
three_mat = np.arange(0,9).reshape((3,3))
three_mat = np.matrix(three_mat)
three_mat

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

11.  Generates an array [[1 2 3] [4 5 6]]

In [43]:
arr_6 = np.arange(1,7).reshape((2,3))
arr_6

array([[1, 2, 3],
       [4, 5, 6]])

12. Generates an array [0 2.5 5 7.5 10]

In [40]:
arr_5 = np.linspace(0,10,5)
arr_5

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

13. Generates an 3x3 array of zeros

In [39]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

14. Create array from 0.1 to 10 with 12 elements, inclusively

In [44]:
arr_12 = np.linspace(0.1,10,12)
arr_12

array([ 0.1,  1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1,
       10. ])

15. Create a matrix with seven columns and five rows of ten(10).

In [47]:
mat_10 = np.matrix(np.full((5,7),10))
mat_10 

matrix([[10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10]])

16. What is the difference between numpy and list?

In [48]:
# Numpy can take multiple dimensions but lists only take a one dimensional input

17. Create a 1D array of ones consisting of  50  values. Change the values of the array so that the values alternate between ones and zeros ie  1,0,1,0,1,0,1,0,1...  ensuring that the starting value is  1 

In [56]:
ones = np.ones(50)
ones[1:51:2] = np.zeros(25)
ones

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.])

18. Generate a  10×10  matrix of zeros.
Make this matrix an identity matrix

In [65]:
mat_zeros = np.eye(10)
mat_zeros = np.matrix(mat_zeros)
mat_zeros

matrix([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

19. Generate an array x to be a  10×10  array of zeros. Redefine its diagonal components (from left to right) to equal one

In [72]:
x = np.zeros((10,10))
np.fill_diagonal(x,1)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

20. What is the dot products of this two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [75]:
mat_a = np.matrix([[1,2],[3,4]])
mat_b = np.matrix([[5,6],[7,8]])
dot = np.dot(mat_a,mat_b)
dot

matrix([[19, 22],
        [43, 50]])

21.  Multiply these two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [3]:
mat_c = np.matrix([[1,2],[3,4]])
mat_d = np.matrix([[5,6],[7,8]])
mat_c*mat_d

matrix([[19, 22],
        [43, 50]])

22. Multiply this matrix  [[1,2],[3,4]] by a  scalar value of 5

In [6]:
s = 5
mat_arr = s* np.matrix([[1,2],[3,4]] )
mat_arr

matrix([[ 5, 10],
        [15, 20]])

23. A = [[1,2],[3,4]] and B = transpose of A. Calculate AxB

In [7]:
A = np.array([[1,2],[3,4]])
B = np.transpose(A)
A_B = A*B
A_B

array([[ 1,  6],
       [ 6, 16]])

24. A= [[1,2],[3,4]] and B =  [[5,6],[7,8]]. Is A x B = B x A ? Show working

In [11]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A*B)
print(B*A)

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


25. Creates an array [[0 1 2] [3 4 5]]
- Let A = first row of the matrix
- B = second row of the matrix
- C = second column of the Matrix
- D = first row, third column of the matrix
- print A , B , C, D

In [21]:
array = np.array([[0, 1, 2], [3, 4, 5]])
A = array[0]
B = array[1]
C = array[:,1]
D = array[0,2]

print(A)
print(B)
print(C)
print(D)

[0 1 2]
[3 4 5]
[1 4]
2
